name: create branch & pull request

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # dev ブランチをチェックアウトする
      - name: checkout dev
        uses: actions/checkout@v2
        with:
          ref: dev

      # プルリクを作成する
      - name: Create Pull Request
        env:
          REVIEWERS: "Hyuga-Tsukui"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.create_branch.outputs.branch_name }}
        run: |
          hub pull-request -m "Github Actions からプルリクを出す" -b stg -h $BRANCH_NAME -l "PR:draft" -r "$REVIEWERS"
