name: create branch & pull request

on:
  delete: [stg]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create Stageing Branch 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b stg
          git push origin stg 
