name: create branch & pull request

on:
  push:
    branches: [prod]

jobs:
  repartition_stage_branch:
    runs-on: ubuntu-latest

    steps:
      - name: checkout prod
        uses: actions/checkout@v2
        with:
          ref: prod

      - name: force push stage branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b stg
          git push -f origin stg
