name: create branch & pull request

on:
  delete

jobs:
  delete_hook:
    runs-on: ubuntu-latest

    steps:
      - name: checkout prod
        uses: actions/checkout@v2
        with:
          ref: prod

      - name: Create Stageing Branch 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo Run only when branch stg is deleted
        if: |
          git checkout -b stg
          git push origin stg 
